-- PARTE 1: Limpieza (Bloque PL/SQL)
-- Ejecuta esto para borrar lo que ya exista
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.AUDITORIAS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.PREMATRICULAS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.HISTORIAS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.DETALLE_PENSUMS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.TERC_PENSUMS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.CURSOS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.PENSUMS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.PROGRAMAS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.ASIGNATURAS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.TERCEROS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
-- El '/' de arriba es VITAL para que Oracle sepa que el bloque terminó.

-- PARTE 2: Creación de Tablas (SQL)

CREATE TABLE SANAYA.TERCEROS (
    TERC_ID NUMBER PRIMARY KEY,
    TERC_TIPO_DOC VARCHAR2(2 BYTE),
    TERC_NRO_DOC VARCHAR2(10 BYTE),
    TERC_GENERO VARCHAR2(1 BYTE),
    TERC_NOMBRES VARCHAR2(50 BYTE),
    TERC_APELLIDOS VARCHAR2(50 BYTE),
    TERC_DIREC VARCHAR2(50 BYTE),
    TERC_CORREO VARCHAR2(50 BYTE),
    TERC_MOVIL VARCHAR2(10 BYTE),
    TERC_TIPO VARCHAR2(1 BYTE)
);

CREATE TABLE SANAYA.ASIGNATURAS (
    ASIG_ID NUMBER PRIMARY KEY,
    ASIG_ASIGNATURA VARCHAR2(50 BYTE),
    ASIG_CREDITOS NUMBER,
    ASIG_CODIGO VARCHAR2(6 BYTE)
);

CREATE TABLE SANAYA.PROGRAMAS (
    PROG_ID NUMBER PRIMARY KEY,
    PROG_PROGRAMA VARCHAR2(50 BYTE)
);

CREATE TABLE SANAYA.CURSOS (
    CURS_ID NUMBER PRIMARY KEY,
    TERC_ID NUMBER,
    ASIG_ID NUMBER,
    CURS_PERIODO VARCHAR2(6 BYTE),
    CONSTRAINT CURSOS_TERC_ID_FK FOREIGN KEY (TERC_ID) REFERENCES SANAYA.TERCEROS(TERC_ID),
    CONSTRAINT CURSOS_ASIG_ID_FK FOREIGN KEY (ASIG_ID) REFERENCES SANAYA.ASIGNATURAS(ASIG_ID)
);

CREATE TABLE SANAYA.PENSUMS (
    PENS_ID NUMBER PRIMARY KEY,
    PROG_ID NUMBER,
    PENS_PERIODO VARCHAR2(6 BYTE),
    CONSTRAINT PENSUMS_PROG_ID_FK FOREIGN KEY (PROG_ID) REFERENCES SANAYA.PROGRAMAS(PROG_ID)
);

CREATE TABLE SANAYA.HISTORIAS (
    HIST_PERIODO VARCHAR2(6 BYTE),
    TERC_ID NUMBER,
    CURS_ID NUMBER,
    HIST_NOTA NUMBER(2,1),
    CONSTRAINT HISTORIAS_CURS_ID_FK FOREIGN KEY (CURS_ID) REFERENCES SANAYA.CURSOS(CURS_ID),
    CONSTRAINT HISTORIAS_TERC_ID_FK FOREIGN KEY (TERC_ID) REFERENCES SANAYA.TERCEROS(TERC_ID),
    CONSTRAINT HISTORIAS_PE_TE_CURS_UK UNIQUE (HIST_PERIODO, TERC_ID, CURS_ID)
);

CREATE TABLE SANAYA.DETALLE_PENSUMS (
    PENS_ID NUMBER,
    ASIG_ID NUMBER,
    DETAPE_NIVEL VARCHAR2(2 BYTE),
    CONSTRAINT DETAPE_PENS_ID_FK FOREIGN KEY (PENS_ID) REFERENCES SANAYA.PENSUMS(PENS_ID),
    CONSTRAINT DETAPE_ASIG_ID_FK FOREIGN KEY (ASIG_ID) REFERENCES SANAYA.ASIGNATURAS(ASIG_ID)
);

CREATE TABLE SANAYA.TERC_PENSUMS (
    PENS_ID NUMBER,
    TERC_ID NUMBER,
    TEPE_PERIODO VARCHAR2(6 BYTE),
    CONSTRAINT TERC_PE_PENS_ID_FK FOREIGN KEY (PENS_ID) REFERENCES SANAYA.PENSUMS(PENS_ID),
    CONSTRAINT TERC_PE_TERC_ID_FK FOREIGN KEY (TERC_ID) REFERENCES SANAYA.TERCEROS(TERC_ID)
);

CREATE TABLE SANAYA.PREMATRICULAS (
    PREM_PERIODO VARCHAR2(6 BYTE),
    TERC_ID NUMBER,
    ASIG_ID NUMBER
);

CREATE TABLE SANAYA.AUDITORIAS (
    AUDI_USUARIO VARCHAR2(50 BYTE),
    AUDI_FECHA TIMESTAMP,
    TERC_ID NUMBER,
    CURS_ID NUMBER,
    HIST_NOTA_ANT NUMBER(2,1),
    HIST_NOTA_DESP NUMBER(2,1)
);

-- PARTE 3: Objetos PL/SQL SANAYA

-- 7) Secuencia para ASIGNATURAS
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SANAYA.SQ_ASIGNATURAS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

CREATE SEQUENCE SANAYA.SQ_ASIGNATURAS
START WITH 54
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 1) Trigger de acceso por dias y horas laborales
CREATE OR REPLACE TRIGGER SANAYA.ACCESO_DIAS_HORAS
    BEFORE INSERT OR UPDATE OR DELETE ON SANAYA.TERCEROS
DECLARE
    -- Evalua siempre contra la zona horaria de negocio.
    V_NOW TIMESTAMP WITH TIME ZONE := SYSTIMESTAMP AT TIME ZONE 'America/Bogota';
    V_DAY VARCHAR2(3);
    V_HHMM NUMBER(4);
BEGIN
    V_DAY := TO_CHAR(V_NOW, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH');
    V_HHMM := TO_NUMBER(TO_CHAR(V_NOW, 'HH24MI'));

    IF V_DAY IN ('SAT', 'SUN')
        OR V_HHMM < 800
        OR V_HHMM > 1800 THEN
        IF DELETING THEN
            RAISE_APPLICATION_ERROR(-20501, 'Usted solo puede borrar registros en dias y horas laborales');
        ELSIF INSERTING THEN
            RAISE_APPLICATION_ERROR(-20502, 'Usted solo puede insertar registros en dias y horas laborales');
        ELSIF UPDATING THEN
            RAISE_APPLICATION_ERROR(-20503, 'Usted solo puede actualizar registros en dias y horas laborales');
        END IF;
    END IF;
END;
/

-- 2) Procedimiento para insertar ASIGNATURAS
CREATE OR REPLACE PROCEDURE SANAYA.SP_ING_ASIGNATURAS (
    P_ASIGNATURA IN VARCHAR2,
    P_CREDITOS IN NUMBER,
    P_CODIGO IN VARCHAR2
) AS
BEGIN
    INSERT INTO SANAYA.ASIGNATURAS (
        ASIG_ID,
        ASIG_ASIGNATURA,
        ASIG_CREDITOS,
        ASIG_CODIGO
    )
    VALUES (
        SANAYA.SQ_ASIGNATURAS.NEXTVAL,
        P_ASIGNATURA,
        P_CREDITOS,
        P_CODIGO
    );

    COMMIT;
END SP_ING_ASIGNATURAS;
/

-- 3) Procedimiento para actualizar ASIGNATURAS
CREATE OR REPLACE PROCEDURE SANAYA.SP_ACT_ASIGNATURAS (
    P_COD IN NUMBER,
    P_ASIGNATURA IN VARCHAR2,
    P_CREDITOS IN NUMBER,
    P_CODIGO IN VARCHAR2
) AS
BEGIN
    UPDATE SANAYA.ASIGNATURAS
        SET ASIG_ASIGNATURA = P_ASIGNATURA,
             ASIG_CREDITOS = P_CREDITOS,
             ASIG_CODIGO = P_CODIGO
     WHERE ASIG_ID = P_COD;

    COMMIT;
END SP_ACT_ASIGNATURAS;
/

-- 4) Procedimiento para eliminar ASIGNATURAS
CREATE OR REPLACE PROCEDURE SANAYA.SP_DEL_ASIGNATURAS (
    P_COD IN NUMBER
) AS
BEGIN
    DELETE FROM SANAYA.ASIGNATURAS
     WHERE ASIG_ID = P_COD;

    COMMIT;
END SP_DEL_ASIGNATURAS;
/

-- 5) Trigger para crear historias iniciales de primer nivel
CREATE OR REPLACE TRIGGER SANAYA.TR_MAT_PRIMIPAROS
    AFTER INSERT ON SANAYA.TERC_PENSUMS
    FOR EACH ROW
BEGIN
    INSERT INTO SANAYA.HISTORIAS (
        HIST_PERIODO,
        TERC_ID,
        CURS_ID,
        HIST_NOTA
    )
    SELECT CASE
                 WHEN TO_NUMBER(TO_CHAR(SYSDATE, 'MM')) BETWEEN 1 AND 6
                 THEN TO_CHAR(SYSDATE, 'YYYY') || '02'
                 ELSE TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY')) + 1) || '01'
             END,
             :NEW.TERC_ID,
             C.CURS_ID,
             NULL
      FROM SANAYA.DETALLE_PENSUMS D
      JOIN SANAYA.CURSOS C
         ON C.ASIG_ID = D.ASIG_ID
     WHERE D.PENS_ID = :NEW.PENS_ID
        AND D.DETAPE_NIVEL = '1';
END;
/

-- 6) Procedimiento de insercion directa en TERC_PENSUMS con periodo manual
CREATE OR REPLACE PROCEDURE SANAYA.SP_ING_TERC_PENSUNS (
    P_CODIGO IN NUMBER,
    P_ID IN NUMBER,
    P_PERIODO IN VARCHAR2
) AS
BEGIN
    INSERT INTO SANAYA.TERC_PENSUMS (
        PENS_ID,
        TERC_ID,
        TEPE_PERIODO
    )
    VALUES (
        P_CODIGO,
        P_ID,
        P_PERIODO
    );

    COMMIT;
END SP_ING_TERC_PENSUNS;
/

-- 8) Procedimiento de insercion en TERC_PENSUMS calculando periodo
CREATE OR REPLACE PROCEDURE SANAYA.SP_ING_TERC_PENSUMS (
    T_ID IN NUMBER,
    P_ID IN NUMBER
) AS
BEGIN
    INSERT INTO SANAYA.TERC_PENSUMS (
        PENS_ID,
        TERC_ID,
        TEPE_PERIODO
    )
    VALUES (
        P_ID,
        T_ID,
        CASE
            WHEN TO_NUMBER(TO_CHAR(SYSDATE, 'MM')) BETWEEN 1 AND 6
            THEN TO_CHAR(SYSDATE, 'YYYY') || '01'
            ELSE TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY')) + 1) || '02'
        END
    );

    COMMIT;
END SP_ING_TERC_PENSUMS;
/

-- 9) Trigger de auditoria de cambios en nota
CREATE OR REPLACE TRIGGER SANAYA.TR_AUDITA_NOTAS
    AFTER UPDATE OF HIST_NOTA ON SANAYA.HISTORIAS
    FOR EACH ROW
BEGIN
    INSERT INTO SANAYA.AUDITORIAS (
        AUDI_USUARIO,
        AUDI_FECHA,
        TERC_ID,
        CURS_ID,
        HIST_NOTA_ANT,
        HIST_NOTA_DESP
    )
    VALUES (
        USER,
        SYSTIMESTAMP,
        :NEW.TERC_ID,
        :NEW.CURS_ID,
        :OLD.HIST_NOTA,
        :NEW.HIST_NOTA
    );
END;
/

-- 10) Vista de auditorias
CREATE OR REPLACE VIEW SANAYA.V_AUDITORIAS AS
SELECT A.AUDI_FECHA AS FECHA,
         A.AUDI_USUARIO AS USUARIO,
         A.TERC_ID,
         T.TERC_NOMBRES,
         T.TERC_APELLIDOS,
         A.CURS_ID,
         B.ASIG_ASIGNATURA,
         A.HIST_NOTA_ANT,
         A.HIST_NOTA_DESP
  FROM SANAYA.AUDITORIAS A
  JOIN SANAYA.TERCEROS T
     ON A.TERC_ID = T.TERC_ID
  JOIN SANAYA.CURSOS C
     ON A.CURS_ID = C.CURS_ID
  JOIN SANAYA.ASIGNATURAS B
     ON C.ASIG_ID = B.ASIG_ID;

-- 11) Funcion de promedio por tercero
CREATE OR REPLACE FUNCTION SANAYA.SP_PROMEDIO (
    P_ID IN NUMBER
) RETURN NUMBER
IS
    V_PROMEDIO NUMBER;
BEGIN
    SELECT ROUND(SUM(H.HIST_NOTA * A.ASIG_CREDITOS) / SUM(A.ASIG_CREDITOS), 2)
      INTO V_PROMEDIO
      FROM SANAYA.HISTORIAS H
      JOIN SANAYA.CURSOS C
         ON H.CURS_ID = C.CURS_ID
      JOIN SANAYA.ASIGNATURAS A
         ON C.ASIG_ID = A.ASIG_ID
     WHERE H.TERC_ID = P_ID;

    RETURN V_PROMEDIO;
END SP_PROMEDIO;
/

-- 12) Vista de promedios
CREATE OR REPLACE VIEW SANAYA.V_PROMEDIOS AS
SELECT TERC_ID AS ID,
         TERC_NOMBRES AS NOMBRES,
         TERC_APELLIDOS AS APELLIDOS,
         SANAYA.SP_PROMEDIO(TERC_ID) AS PROMEDIO
  FROM SANAYA.TERCEROS
 WHERE TERC_TIPO = '0';
