-- PARTE 1: Limpieza (Bloque PL/SQL)
-- Ejecuta esto para borrar lo que ya exista
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.AUDITORIAS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.PREMATRICULAS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.HISTORIAS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.DETALLE_PENSUMS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.TERC_PENSUMS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.CURSOS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.PENSUMS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.PROGRAMAS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.ASIGNATURAS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SANAYA.TERCEROS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
-- El '/' de arriba es VITAL para que Oracle sepa que el bloque terminó.

-- PARTE 2: Creación de Tablas (SQL)

CREATE TABLE SANAYA.TERCEROS (
    TERC_ID NUMBER PRIMARY KEY,
    TERC_TIPO_DOC VARCHAR2(2 BYTE),
    TERC_NRO_DOC VARCHAR2(10 BYTE),
    TERC_GENERO VARCHAR2(1 BYTE),
    TERC_NOMBRES VARCHAR2(50 BYTE),
    TERC_APELLIDOS VARCHAR2(50 BYTE),
    TERC_DIREC VARCHAR2(50 BYTE),
    TERC_CORREO VARCHAR2(50 BYTE),
    TERC_MOVIL VARCHAR2(10 BYTE),
    TERC_TIPO VARCHAR2(1 BYTE)
);

CREATE TABLE SANAYA.ASIGNATURAS (
    ASIG_ID NUMBER PRIMARY KEY,
    ASIG_ASIGNATURA VARCHAR2(50 BYTE),
    ASIG_CREDITOS NUMBER,
    ASIG_CODIGO VARCHAR2(6 BYTE)
);

CREATE TABLE SANAYA.PROGRAMAS (
    PROG_ID NUMBER PRIMARY KEY,
    PROG_PROGRAMA VARCHAR2(50 BYTE)
);

CREATE TABLE SANAYA.CURSOS (
    CURS_ID NUMBER PRIMARY KEY,
    TERC_ID NUMBER,
    ASIG_ID NUMBER,
    CURS_PERIODO VARCHAR2(6 BYTE),
    CONSTRAINT CURSOS_TERC_ID_FK FOREIGN KEY (TERC_ID) REFERENCES SANAYA.TERCEROS(TERC_ID),
    CONSTRAINT CURSOS_ASIG_ID_FK FOREIGN KEY (ASIG_ID) REFERENCES SANAYA.ASIGNATURAS(ASIG_ID)
);

CREATE TABLE SANAYA.PENSUMS (
    PENS_ID NUMBER PRIMARY KEY,
    PROG_ID NUMBER,
    PENS_PERIODO VARCHAR2(6 BYTE),
    CONSTRAINT PENSUMS_PROG_ID_FK FOREIGN KEY (PROG_ID) REFERENCES SANAYA.PROGRAMAS(PROG_ID)
);

CREATE TABLE SANAYA.HISTORIAS (
    HIST_PERIODO VARCHAR2(6 BYTE),
    TERC_ID NUMBER,
    CURS_ID NUMBER,
    HIST_NOTA NUMBER(2,1),
    CONSTRAINT HISTORIAS_CURS_ID_FK FOREIGN KEY (CURS_ID) REFERENCES SANAYA.CURSOS(CURS_ID),
    CONSTRAINT HISTORIAS_TERC_ID_FK FOREIGN KEY (TERC_ID) REFERENCES SANAYA.TERCEROS(TERC_ID),
    CONSTRAINT HISTORIAS_PE_TE_CURS_UK UNIQUE (HIST_PERIODO, TERC_ID, CURS_ID)
);

CREATE TABLE SANAYA.DETALLE_PENSUMS (
    PENS_ID NUMBER,
    ASIG_ID NUMBER,
    DETAPE_NIVEL VARCHAR2(2 BYTE),
    CONSTRAINT DETAPE_PENS_ID_FK FOREIGN KEY (PENS_ID) REFERENCES SANAYA.PENSUMS(PENS_ID),
    CONSTRAINT DETAPE_ASIG_ID_FK FOREIGN KEY (ASIG_ID) REFERENCES SANAYA.ASIGNATURAS(ASIG_ID)
);

CREATE TABLE SANAYA.TERC_PENSUMS (
    PENS_ID NUMBER,
    TERC_ID NUMBER,
    TEPE_PERIODO VARCHAR2(6 BYTE),
    CONSTRAINT TERC_PE_PENS_ID_FK FOREIGN KEY (PENS_ID) REFERENCES SANAYA.PENSUMS(PENS_ID),
    CONSTRAINT TERC_PE_TERC_ID_FK FOREIGN KEY (TERC_ID) REFERENCES SANAYA.TERCEROS(TERC_ID)
);

CREATE TABLE SANAYA.PREMATRICULAS (
    PREM_PERIODO VARCHAR2(6 BYTE),
    TERC_ID NUMBER,
    ASIG_ID NUMBER
);

CREATE TABLE SANAYA.AUDITORIAS (
    AUDI_USUARIO VARCHAR2(50 BYTE),
    AUDI_FECHA TIMESTAMP,
    TERC_ID NUMBER,
    CURS_ID NUMBER,
    HIST_NOTA_ANT NUMBER(2,1),
    HIST_NOTA_DESP NUMBER(2,1)
);
