import bcrypt from "bcrypt";
import dotenv from "dotenv";

import { sequelize } from "../config/sequelize.js";
import models from "../models/index.js";

dotenv.config();

const DEFAULT_ADMIN = {
  email: process.env.ADMIN_EMAIL || "admin@sanaya.local",
  password: process.env.ADMIN_PASSWORD || "admin123",
  nombres: process.env.ADMIN_NOMBRES || "Super",
  apellidos: process.env.ADMIN_APELLIDOS || "Admin",
  rol: "SUPER_ADMIN",
};

const ensureAuthTable = async () => {
  await sequelize.query(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE APP_USUARIOS (
          USUA_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          USUA_EMAIL VARCHAR2(100 BYTE) NOT NULL UNIQUE,
          USUA_PASSWORD VARCHAR2(255 BYTE) NOT NULL,
          USUA_NOMBRES VARCHAR2(60 BYTE) NOT NULL,
          USUA_APELLIDOS VARCHAR2(60 BYTE) NOT NULL,
          USUA_ROL VARCHAR2(20 BYTE) DEFAULT ''ADMIN'' NOT NULL,
          USUA_ESTADO NUMBER(1) DEFAULT 1 NOT NULL
        )';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;
  `);
};

const ensureAdmin = async () => {
  const admin = await models.AppUsuario.findOne({
    where: { usua_email: DEFAULT_ADMIN.email },
  });

  if (admin) {
    console.info("ℹ️ Usuario administrador ya existe");
    return;
  }

  const hash = await bcrypt.hash(DEFAULT_ADMIN.password, 10);
  await models.AppUsuario.create({
    usua_email: DEFAULT_ADMIN.email,
    usua_password: hash,
    usua_nombres: DEFAULT_ADMIN.nombres,
    usua_apellidos: DEFAULT_ADMIN.apellidos,
    usua_rol: DEFAULT_ADMIN.rol,
    usua_estado: 1,
  });

  console.info(`✅ Admin creado: ${DEFAULT_ADMIN.email}`);
};

const init = async () => {
  try {
    await sequelize.authenticate();
    console.info("✅ Conexión a Oracle establecida");

    await ensureAuthTable();
    console.info("✅ Tabla APP_USUARIOS validada");

    await ensureAdmin();

    console.info("✅ Inicialización completada");
    process.exit(0);
  } catch (error) {
    console.error("❌ Error en init:", error.message);
    process.exit(1);
  }
};

init();
