import bcrypt from "bcrypt";
import dotenv from "dotenv";

import { sequelize } from "../config/sequelize.js";
import models from "../models/index.js";

dotenv.config();

const DEFAULT_ADMINS = [
  {
    email: process.env.ADMIN_EMAIL || "admin@sanaya.local",
    password: process.env.ADMIN_PASSWORD || "admin123",
    nombres: process.env.ADMIN_NOMBRES || "Super",
    apellidos: process.env.ADMIN_APELLIDOS || "Admin",
    rol: "SUPER_ADMIN",
  },
  {
    email: process.env.ADMIN_EMAIL_SECONDARY || "admin@sanaya.com",
    password: process.env.ADMIN_PASSWORD_SECONDARY || "123456",
    nombres: process.env.ADMIN_NOMBRES_SECONDARY || "Admin",
    apellidos: process.env.ADMIN_APELLIDOS_SECONDARY || "Secundario",
    rol: "SUPER_ADMIN",
  },
];

const ensureAuthTable = async () => {
  await sequelize.query(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE APP_USUARIOS (
          USUA_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          USUA_EMAIL VARCHAR2(100 BYTE) NOT NULL UNIQUE,
          USUA_PASSWORD VARCHAR2(255 BYTE) NOT NULL,
          USUA_NOMBRES VARCHAR2(60 BYTE) NOT NULL,
          USUA_APELLIDOS VARCHAR2(60 BYTE) NOT NULL,
          USUA_ROL VARCHAR2(20 BYTE) DEFAULT ''ADMIN'' NOT NULL,
          USUA_ESTADO NUMBER(1) DEFAULT 1 NOT NULL
        )';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;
  `);
};

const ensureAdmins = async () => {
  for (const adminConfig of DEFAULT_ADMINS) {
    const admin = await models.AppUsuario.findOne({
      where: { usua_email: adminConfig.email },
    });

    if (admin) {
      console.info(`ℹ️ Usuario administrador ya existe: ${adminConfig.email}`);
      continue;
    }

    const hash = await bcrypt.hash(adminConfig.password, 10);
    await models.AppUsuario.create({
      usua_email: adminConfig.email,
      usua_password: hash,
      usua_nombres: adminConfig.nombres,
      usua_apellidos: adminConfig.apellidos,
      usua_rol: adminConfig.rol,
      usua_estado: 1,
    });

    console.info(`✅ Admin creado: ${adminConfig.email}`);
  }
};

const init = async () => {
  try {
    await sequelize.authenticate();
    console.info("✅ Conexión a Oracle establecida");

    await ensureAuthTable();
    console.info("✅ Tabla APP_USUARIOS validada");

    await ensureAdmins();

    console.info("✅ Inicialización completada");
    process.exit(0);
  } catch (error) {
    console.error("❌ Error en init:", error.message);
    process.exit(1);
  }
};

init();
